# -*- coding: utf-8 -*-
"""Hex Color Code

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17zPcJjmJhFoptUB0xZX1AjEnG-RyYaff
"""

import re

for i in range(0,int(input())):
    code=input()

    x=code.split()

    if len(x)>1  and  '{' not in x:
        x=re.findall(r'#[a-fA-F0-9]{3,6}',code)
        [print(i) for  i in x]