# -*- coding: utf-8 -*-
"""Detect Floating Point Number

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17zPcJjmJhFoptUB0xZX1AjEnG-RyYaff
"""

import re
regex_pattern = r",|\."	# Do not delete 'r'.
print("\n".join(re.split(regex_pattern, input())))