# -*- coding: utf-8 -*-
"""Re.start() & Re.end()

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17zPcJjmJhFoptUB0xZX1AjEnG-RyYaff
"""

# Re.start() & Re.end()

import re

S = input()
k = input()

i = re.compile(k)
r = i.search(S)
if not r: 
    print ("(-1, -1)")
while r:
    print ("({0}, {1})".format(r.start(), r.end() - 1))
    r = i.search(S,r.start() + 1)