# -*- coding: utf-8 -*-
"""Validating Credit Card Numbers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17zPcJjmJhFoptUB0xZX1AjEnG-RyYaff
"""

# Validating Credit Card Numbers
import re
for _ in range(int(input().strip())):
    print("Valid" if re.search(r"^(?!.*(\d)(-?\1){3})[456]\d{3}(?:-?\d{4}){3}$",input().strip()) else "Invalid")